// <auto-generated />
namespace FoodOrderSolution.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addreplyfeedback : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addreplyfeedback));
        
        string IMigrationMetadata.Id
        {
            get { return "202005021651559_add-reply-feedback"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
