// <auto-generated />
namespace FoodOrderSolution.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updatevoucherfiled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatevoucherfiled));
        
        string IMigrationMetadata.Id
        {
            get { return "202005050404075_update-voucher-filed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
