// <auto-generated />
namespace FoodOrderSolution.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class updatememberstatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatememberstatus));
        
        string IMigrationMetadata.Id
        {
            get { return "202005131027131_update-member-status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
