// <auto-generated />
namespace FoodOrderSolution.Services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class removetag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removetag));
        
        string IMigrationMetadata.Id
        {
            get { return "202004241617386_remove-tag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
